#!/usr/bin/env python3
"""Overlay Hessian top-eigen trends for two methods with tone-based color families.

Expected input files are trend_data.json (preferred) or trend_data.csv generated by
src/runners/checkpoint_trend.py for metric=hessian_eigenvalues.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def _eig_key(rank: int) -> str:
    return f"hessian.top_eig_{rank}"


def _parse_rank_from_key(key: str) -> int | None:
    prefix = "hessian.top_eig_"
    if not key.startswith(prefix):
        return None
    try:
        return int(key[len(prefix):])
    except Exception:
        return None


def _load_from_json(path: Path) -> tuple[np.ndarray, dict[int, np.ndarray]]:
    payload = json.loads(path.read_text())
    steps = np.asarray(payload.get("steps", []), dtype=float)
    series = payload.get("series", {})

    rank_series: dict[int, np.ndarray] = {}
    if isinstance(series, dict):
        for key, values in series.items():
            rank = _parse_rank_from_key(str(key))
            if rank is None:
                continue
            rank_series[rank] = np.asarray(values, dtype=float)

    return steps, rank_series


def _load_from_csv(path: Path) -> tuple[np.ndarray, dict[int, np.ndarray]]:
    rows: list[dict[str, str]] = []
    with path.open("r", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows.append({k: (v or "") for k, v in row.items()})

    if not rows:
        return np.asarray([], dtype=float), {}

    steps = []
    for row in rows:
        try:
            steps.append(float(row.get("step", "")))
        except Exception:
            steps.append(np.nan)
    step_arr = np.asarray(steps, dtype=float)

    rank_series: dict[int, np.ndarray] = {}
    for key in rows[0].keys():
        rank = _parse_rank_from_key(key)
        if rank is None:
            continue
        vals = []
        for row in rows:
            text = str(row.get(key, "")).strip()
            if not text:
                vals.append(np.nan)
                continue
            try:
                vals.append(float(text))
            except Exception:
                vals.append(np.nan)
        rank_series[rank] = np.asarray(vals, dtype=float)

    return step_arr, rank_series


def load_trend(path_str: str) -> tuple[np.ndarray, dict[int, np.ndarray]]:
    path = Path(path_str)
    if not path.exists():
        raise FileNotFoundError(f"Trend file not found: {path}")

    if path.suffix.lower() == ".json":
        return _load_from_json(path)
    if path.suffix.lower() == ".csv":
        return _load_from_csv(path)

    raise ValueError("Trend file must be .json or .csv")


def _tone_colors(cmap_name: str, top_k: int) -> list[Any]:
    cmap = plt.get_cmap(cmap_name)
    # Dark -> light (eig_1 darkest)
    tone_values = np.linspace(0.85, 0.35, top_k)
    return [cmap(v) for v in tone_values]


def _plot_model_series(
    ax: plt.Axes,
    steps: np.ndarray,
    rank_series: dict[int, np.ndarray],
    label_prefix: str,
    cmap_name: str,
    top_k: int,
) -> None:
    colors = _tone_colors(cmap_name, top_k)
    for rank in range(1, top_k + 1):
        values = rank_series.get(rank)
        if values is None:
            continue
        y = np.asarray(values, dtype=float)
        n = min(len(steps), len(y))
        if n == 0:
            continue
        x = steps[:n]
        y = y[:n]
        mask = (~np.isnan(x)) & (~np.isnan(y))
        if not np.any(mask):
            continue
        ax.plot(
            x[mask],
            y[mask],
            marker="o",
            linewidth=1.9,
            markersize=4.5,
            color=colors[rank - 1],
            label=f"{label_prefix} eig_{rank}",
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Overlay Hessian top-eigen trends for LLaMA and CoLA")
    parser.add_argument("--llama_trend", required=True, help="Path to llama trend_data.json or trend_data.csv")
    parser.add_argument("--cola_trend", required=True, help="Path to cola trend_data.json or trend_data.csv")
    parser.add_argument("--top_k", type=int, default=8, help="Number of eig ranks to plot")
    parser.add_argument("--llama_label", default="llama", help="Legend label prefix for llama")
    parser.add_argument("--cola_label", default="cola", help="Legend label prefix for cola")
    parser.add_argument("--title", default="Hessian top-eigen trend: llama vs cola")
    parser.add_argument("--output_dir", default="output/hessian_overlay")
    parser.add_argument("--fname", default="hessian_overlay")
    parser.add_argument("--dpi", type=int, default=220)
    args = parser.parse_args()

    llama_steps, llama_series = load_trend(args.llama_trend)
    cola_steps, cola_series = load_trend(args.cola_trend)

    if llama_steps.size == 0 and cola_steps.size == 0:
        raise SystemExit("No valid trend data found in both inputs")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(12, 7))
    _plot_model_series(ax, llama_steps, llama_series, args.llama_label, "Blues", args.top_k)
    _plot_model_series(ax, cola_steps, cola_series, args.cola_label, "Oranges", args.top_k)

    ax.set_title(args.title, fontsize=16)
    ax.set_xlabel("Checkpoint Step", fontsize=13)
    ax.set_ylabel("Mean top-k eigenvalue", fontsize=13)
    ax.grid(True, alpha=0.3)
    ax.legend(ncol=4, fontsize=9, frameon=False)

    plt.tight_layout()
    png = output_dir / f"{args.fname}.png"
    pdf = output_dir / f"{args.fname}.pdf"
    fig.savefig(png, dpi=args.dpi)
    fig.savefig(pdf)
    plt.close(fig)

    print(f"Saved PNG: {png}")
    print(f"Saved PDF: {pdf}")


if __name__ == "__main__":
    main()
